######################################################################
# Automatically generated by qmake (3.0) Mon May 27 16:42:59 2013
######################################################################


QMAKE_CXXFLAGS += -std=c++11
QT += core gui widgets	


TEMPLATE = app
TARGET = P4
INCLUDEPATH += .

# Input
HEADERS += baseboggleplayer.h boggleboard.h mainwindow.h ui_mainwindow.h
FORMS += mainwindow.ui
SOURCES += boggleboard.cpp main.cpp mainwindow.cpp
